//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Combat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mission
    {
        public int Id { get; set; }
        public int foe1Class { get; set; }
        public int foe1Level { get; set; }
        public Nullable<int> foe2Class { get; set; }
        public Nullable<int> foe2Level { get; set; }
        public Nullable<int> foe3Class { get; set; }
        public Nullable<int> foe3Level { get; set; }
        public Nullable<int> foe4Class { get; set; }
        public Nullable<int> foe4Level { get; set; }
        public string Name { get; set; }
    }
}
